[versions]
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter
kotlin = "1.9.21"
spring-boot = "3.2.1"
spring-dependency-management = "1.1.4"

# https://mvnrepository.com/artifact/software.amazon.awssdk/bom
aws-java-sdk-v2 = "2.20.144"

# https://mvnrepository.com/artifact/com.mybatis-flex/mybatis-flex-spring-boot-starter
mybatis-flex = "1.7.6"

# https://mvnrepository.com/artifact/com.mybatis-flex/mybatis-flex-kotlin-extensions
mybatis-flex-kotlin-extensions = "1.0.5"

mybatis-spring = "3.0.3"

hikari-cp = "5.0.1"

# https://mvnrepository.com/artifact/com.ninja-squad/springmockk
spring-mockk = "4.0.2"

# https://mvnrepository.com/artifact/org.redisson/redisson
redisson = "3.23.4"

# https://mvnrepository.com/artifact/org.jetbrains.exposed/exposed-spring-boot-starter
exposed = "0.44.0"

# https://mvnrepository.com/artifact/io.arrow-kt/arrow-core
arrow-kt = "1.2.1"

# https://mvnrepository.com/artifact/com.linecorp.kotlin-jdsl/kotlin-jdsl
jpql-jdsl = "3.0.0"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

[libraries]
# boms
aws-bom = { module = "software.amazon.awssdk:bom", version.ref = "aws-java-sdk-v2" }

# spring boot
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-tomcat = { module = "org.springframework.boot:spring-boot-starter-tomcat" }
spring-boot-starter-undertow = { module = "org.springframework.boot:spring-boot-starter-undertow" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }

undertow-websockets = { module = "io.undertow:undertow-websockets-jsr" }
spring-web = { module = "org.springframework:spring-web" }
spring-webmvc = { module = "org.springframework:spring-webmvc" }
servlet-api = { module = "jakarta.servlet:jakarta.servlet-api" }
slf4j-api = { module = "org.slf4j:slf4j-api" }

# netty
netty-dns-macos = { module = "io.netty:netty-resolver-dns-native-macos" }

# kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }

# jackson
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
jackson-datatype-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8" }

# mybatis
mybatis-flex-spring-boot-starter = { module = "com.mybatis-flex:mybatis-flex-spring-boot-starter", version.ref = "mybatis-flex" }
mybatis-flex-kotlin-extensions = { module = "com.mybatis-flex:mybatis-flex-kotlin-extensions", version.ref = "mybatis-flex-kotlin-extensions" }
mybatis-spring = { module = "org.mybatis:mybatis-spring", version.ref = "mybatis-spring" }
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari-cp" }
mysql-connector-j = { module = "com.mysql:mysql-connector-j" }

# mockk
springmockk = { module = "com.ninja-squad:springmockk", version.ref = "spring-mockk" }

# awssdk
awssdk-auth = { module = "software.amazon.awssdk:auth" }
awssdk-dynamodb = { module = "software.amazon.awssdk:dynamodb" }
awssdk-dynamodb-enhanced = { module = "software.amazon.awssdk:dynamodb-enhanced" }
awssdk-cloudwatchlogs = { module = "software.amazon.awssdk:cloudwatchlogs" }
awssdk-ec2 = { module = "software.amazon.awssdk:ec2" }
awssdk-s3 = { module = "software.amazon.awssdk:s3" }
awssdk-sqs = { module = "software.amazon.awssdk:sqs" }

# redisson
redisson = { module = "org.redisson:redisson", version.ref = "redisson" }
commons-pool2 = { module = "org.apache.commons:commons-pool2" }

# exposed
exposed = { module = "org.jetbrains.exposed:exposed-spring-boot-starter", version.ref = "exposed" }

# arrow-kt
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow-kt" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow-kt" }

# kotlin-jdsl
jpql-dsl = { module = "com.linecorp.kotlin-jdsl:jpql-dsl", version.ref = "jpql-jdsl" }
jpql-render = { module = "com.linecorp.kotlin-jdsl:jpql-render", version.ref = "jpql-jdsl" }
jpql-spring-data-jpa-support = { module = "com.linecorp.kotlin-jdsl:spring-data-jpa-support", version.ref = "jpql-jdsl" }

[bundles]
kotlin = ["kotlin-reflect", "kotlin-stdlib-jdk8"]
kotlin-coroutines = ["kotlinx-coroutines-core", "kotlinx-coroutines-reactor"]
jackson = ["jackson-module-kotlin", "jackson-datatype-jsr310", "jackson-datatype-jdk8"]
arrow-kt = ["arrow-core", "arrow-fx-coroutines"]
jpql-jdsl = ["jpql-dsl", "jpql-render", "jpql-spring-data-jpa-support"]
